

export default function getRandomAvatar() {
    const avatars = [
        require('../../assets/avatars/avataaars.png'),
        require('../../assets/avatars/avataaars1.png'),
        require('../../assets/avatars/avataaars2.png'),
        require('../../assets/avatars/avataaars3.png'),
        require('../../assets/avatars/avataaars4.png'),
        require('../../assets/avatars/avataaars5.png'),
        require('../../assets/avatars/avataaars6.png'),
        require('../../assets/avatars/avataaars7.png'),
        require('../../assets/avatars/avataaars8.png'),
        require('../../assets/avatars/avataaars9.png'),
        require('../../assets/avatars/avataaars10.png'),
        require('../../assets/avatars/avataaars11.png'),
        require('../../assets/avatars/avataaars12.png'),
        require('../../assets/avatars/avataaars13.png'),
        require('../../assets/avatars/avataaars14.png'),
        require('../../assets/avatars/avataaars15.png'),
        require('../../assets/avatars/avataaars16.png'),
        require('../../assets/avatars/avataaars17.png'),
        require('../../assets/avatars/avataaars18.png'),
        require('../../assets/avatars/avataaars19.png'),
        require('../../assets/avatars/avataaars20.png'),
        require('../../assets/avatars/avataaars21.png'),
        require('../../assets/avatars/avataaars22.png'),
        require('../../assets/avatars/avataaars23.png'),
        require('../../assets/avatars/avataaars24.png'),
        require('../../assets/avatars/avataaars25.png'),
        require('../../assets/avatars/avataaars26.png'),
        require('../../assets/avatars/avataaars(7).png'),
        require('../../assets/avatars/avataaars(8).png'),
        require('../../assets/avatars/avataaars(9).png'),
        require('../../assets/avatars/avataaars(10).png'),
        require('../../assets/avatars/avataaars(11).png'),
        require('../../assets/avatars/avataaars(12).png'),
        require('../../assets/avatars/avataaars(13).png'),
        require('../../assets/avatars/avataaars(14).png'),
        require('../../assets/avatars/avataaars(15).png'),
        require('../../assets/avatars/avataaars(16).png'),
        require('../../assets/avatars/avataaars(17).png'),
        require('../../assets/avatars/avataaars(18).png'),
        require('../../assets/avatars/avataaars(19).png'),
        require('../../assets/avatars/avataaars(20).png'),
        require('../../assets/avatars/avataaars(21).png'),
        require('../../assets/avatars/avataaars(22).png'),
        require('../../assets/avatars/avataaars(23).png'),
        require('../../assets/avatars/avataaars(24).png'),
        require('../../assets/avatars/avataaars(25).png'),
        require('../../assets/avatars/avataaars(26).png'),
        require('../../assets/avatars/avataaars(27).png'),
        require('../../assets/avatars/avataaars(28).png'),
        require('../../assets/avatars/avataaars(29).png'),
        require('../../assets/avatars/avataaars(30).png'),
    ]
    return avatars[Math.floor(Math.random() * avatars.length)];
}
